name: emle

channels:
  - conda-forge

dependencies:
  - ase
  - h5py
  - loguru
  - nnpops
  - numpy
  - pygit2
  - python >=3.10
  - pytorch
  - pyyaml
  - scipy
  - setuptools <81
  - torchani >=2.7
