name: emle

channels:
  - conda-forge

dependencies:
  - ambertools
  - ase
  - deepmd-kit
  - loguru
  - pip
  - psutil
  - pygit2
  - pytorch >= 2.7
  - python
  - pyyaml
  - setuptools < 81
  - xtb-python
  - pip:
    - mace-torch
    - torchani >= 2.7
