[build-system]
requires = ["setuptools>=61.0.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "emle-engine"
description = "An engine for electrostatic machine learned embedding potentials"
authors = [
    { name = "Lester Hedges", email = "lester.hedges@gmail.com" },
]
license = { text = "GPL-2.0-only" }
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/chemle/emle-engine"

[tool.setuptools]
include-package-data = true
zip-safe = false
script-files = [
    "bin/emle-analyze",
    "bin/emle-compile",
    "bin/emle-server",
    "bin/emle-stop",
    "bin/emle-train",
    "bin/orca",
    "bin/tarball-to-extxyz",
]

[tool.setuptools.packages.find]
include = ["emle", "emle.*"]

[tool.setuptools_scm]
version_scheme = "post-release"